'use client';

import { useRef, useEffect, useState } from 'react';
import { motion, useInView } from 'motion/react';

const sections = [
  {
    id: 'acceptance-of-terms',
    number: '01',
    title: 'Acceptance of Terms',
    content: (
      <p>
        By accessing or using ZGNAL.AI (&ldquo;the Service&rdquo;), you agree to be bound by these
        Terms of Service. If you do not agree, do not use the Service.
      </p>
    ),
  },
  {
    id: 'description-of-service',
    number: '02',
    title: 'Description of Service',
    content: (
      <p>
        ZGNAL.AI is an AI-powered infographic generation platform. The Service uses artificial
        intelligence to transform user-submitted content into visual infographics. Results are
        generated algorithmically and may vary.
      </p>
    ),
  },
  {
    id: 'user-content',
    number: '03',
    title: 'User Content',
    content: (
      <p>
        You retain ownership of all content you submit to the Service. By submitting content, you
        grant ZGNAL.AI a temporary license to process it through our pipeline for the purpose of
        generating your infographic. You are responsible for ensuring you have the right to use any
        content you submit.
      </p>
    ),
  },
  {
    id: 'generated-content',
    number: '04',
    title: 'Generated Content',
    content: (
      <p>
        Infographics generated by the Service are created using AI models. You may use generated
        infographics for personal and commercial purposes. Generated content comes with a provenance
        certificate documenting the creation methodology. ZGNAL.AI does not claim ownership of
        generated infographics.
      </p>
    ),
  },
  {
    id: 'acceptable-use',
    number: '05',
    title: 'Acceptable Use',
    content: (
      <ul className="list-disc list-inside space-y-2 pl-2">
        <li>Do not submit content that violates third-party rights</li>
        <li>Do not use the Service to generate misleading or harmful content</li>
        <li>Do not attempt to reverse-engineer the pipeline or AI models</li>
        <li>Do not use automated systems to abuse the Service</li>
      </ul>
    ),
  },
  {
    id: 'disclaimers',
    number: '06',
    title: 'Disclaimers',
    content: (
      <p>
        The Service is provided &ldquo;as is&rdquo; without warranties of any kind. AI-generated
        content may contain inaccuracies. Users should verify factual claims in generated
        infographics before publication.
      </p>
    ),
  },
  {
    id: 'limitation-of-liability',
    number: '07',
    title: 'Limitation of Liability',
    content: (
      <p>
        ZGNAL.AI shall not be liable for any indirect, incidental, or consequential damages arising
        from use of the Service.
      </p>
    ),
  },
  {
    id: 'changes-to-terms',
    number: '08',
    title: 'Changes to Terms',
    content: (
      <p>
        We reserve the right to modify these terms at any time. Continued use of the Service
        constitutes acceptance of updated terms.
      </p>
    ),
  },
];

function Section({
  section,
  onVisible,
}: {
  section: (typeof sections)[number];
  onVisible: (id: string) => void;
}) {
  const ref = useRef<HTMLElement>(null);
  const isInView = useInView(ref, { once: true, margin: '-80px' });
  const isActive = useInView(ref, { margin: '-50% 0px -50% 0px' });

  useEffect(() => {
    if (isActive) onVisible(section.id);
  }, [isActive, section.id, onVisible]);

  return (
    <motion.section
      ref={ref}
      id={section.id}
      initial={{ opacity: 0, y: 24 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 24 }}
      transition={{ duration: 0.5, ease: [0.25, 0.1, 0.25, 1] }}
      className="scroll-mt-28"
    >
      <div className="flex items-baseline gap-4 mb-4">
        <span className="text-[#D4A84B] font-mono text-xs font-bold tracking-wider">
          {section.number}
        </span>
        <h2 className="text-base font-mono font-bold text-white">{section.title}</h2>
      </div>
      <div className="text-sm text-white/50 leading-relaxed pl-10">{section.content}</div>
    </motion.section>
  );
}

export default function TermsPage() {
  const [activeId, setActiveId] = useState(sections[0].id);

  return (
    <div className="mx-auto max-w-6xl px-6 py-20 sm:py-28">
      {/* Hero */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: [0.25, 0.1, 0.25, 1] }}
        className="max-w-3xl mb-10"
      >
        <p className="text-[10px] font-mono font-semibold tracking-[0.2em] uppercase text-[#D4A84B] mb-4">
          Legal
        </p>
        <h1 className="text-3xl sm:text-4xl lg:text-5xl font-mono font-bold text-white mb-2">
          Terms of Service
        </h1>
        <p className="text-xs font-mono text-white/30 mb-8">Last updated: March 2026</p>
      </motion.div>

      {/* TL;DR Box */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.15, ease: [0.25, 0.1, 0.25, 1] }}
        className="max-w-3xl border-2 border-[#D4A84B]/30 bg-[#D4A84B]/4 p-6 mb-16"
      >
        <p className="text-[9px] font-mono font-semibold tracking-[0.2em] uppercase text-[#D4A84B] mb-2">
          TL;DR
        </p>
        <p className="text-sm text-white/70 leading-relaxed">
          <span className="font-semibold text-white">You own your content</span> and{' '}
          <span className="font-semibold text-white">your generated infographics.</span> Use the
          service responsibly.
        </p>
      </motion.div>

      {/* Divider */}
      <div className="h-px bg-linear-to-r from-[#D4A84B]/30 via-[#D4A84B]/10 to-transparent mb-16" />

      {/* Content + Sidebar */}
      <div className="flex gap-16">
        {/* Main content */}
        <div className="flex-1 max-w-3xl space-y-12">
          {sections.map((section, i) => (
            <div key={section.id}>
              <Section section={section} onVisible={setActiveId} />
              {i < sections.length - 1 && (
                <div className="h-px bg-linear-to-r from-[#D4A84B]/20 via-[#D4A84B]/5 to-transparent mt-12" />
              )}
            </div>
          ))}

          {/* Contact callout */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.5 }}
            className="border-2 border-[#D4A84B]/30 p-8 mt-16"
          >
            <p className="text-[9px] font-mono font-semibold tracking-[0.2em] uppercase text-[#D4A84B] mb-3">
              Questions?
            </p>
            <p className="text-sm text-white/60 leading-relaxed">
              For questions about these terms, reach out to{' '}
              <a href="mailto:hello@zgnal.ai" className="text-[#D4A84B] hover:underline font-mono">
                hello@zgnal.ai
              </a>
            </p>
          </motion.div>
        </div>

        {/* Sidebar TOC — desktop only */}
        <aside className="hidden lg:block w-56 shrink-0">
          <nav className="sticky top-28">
            <p className="text-[9px] font-mono font-semibold tracking-[0.2em] uppercase text-white/30 mb-4">
              On this page
            </p>
            <ul className="space-y-2">
              {sections.map((section) => (
                <li key={section.id}>
                  <a
                    href={`#${section.id}`}
                    className={`flex items-center gap-2 text-xs font-mono transition-colors duration-200 ${
                      activeId === section.id
                        ? 'text-[#D4A84B]'
                        : 'text-white/25 hover:text-white/50'
                    }`}
                  >
                    <span className="w-5 text-right shrink-0">{section.number}</span>
                    <span className="truncate">{section.title}</span>
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </aside>
      </div>
    </div>
  );
}
