import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — ZGNAL.AI',
  description: 'Terms and conditions for using ZGNAL.AI.',
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-20 sm:py-28">
      <p className="text-[10px] font-mono font-semibold tracking-[0.2em] uppercase text-[#D4A84B] mb-4">Legal</p>
      <h1 className="text-3xl sm:text-4xl font-mono font-bold text-white mb-2">Terms of Service</h1>
      <p className="text-xs font-mono text-white/30 mb-12">Last updated: March 2026</p>

      <div className="space-y-8 text-sm text-white/50 leading-relaxed">
        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using ZGNAL.AI (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">2. Description of Service</h2>
          <p>ZGNAL.AI is an AI-powered infographic generation platform. The Service uses artificial intelligence to transform user-submitted content into visual infographics. Results are generated algorithmically and may vary.</p>
        </section>

        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">3. User Content</h2>
          <p>You retain ownership of all content you submit to the Service. By submitting content, you grant ZGNAL.AI a temporary license to process it through our pipeline for the purpose of generating your infographic. You are responsible for ensuring you have the right to use any content you submit.</p>
        </section>

        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">4. Generated Content</h2>
          <p>Infographics generated by the Service are created using AI models. You may use generated infographics for personal and commercial purposes. Generated content comes with a provenance certificate documenting the creation methodology. ZGNAL.AI does not claim ownership of generated infographics.</p>
        </section>

        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">5. Acceptable Use</h2>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>Do not submit content that violates third-party rights</li>
            <li>Do not use the Service to generate misleading or harmful content</li>
            <li>Do not attempt to reverse-engineer the pipeline or AI models</li>
            <li>Do not use automated systems to abuse the Service</li>
          </ul>
        </section>

        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">6. Disclaimers</h2>
          <p>The Service is provided &ldquo;as is&rdquo; without warranties of any kind. AI-generated content may contain inaccuracies. Users should verify factual claims in generated infographics before publication.</p>
        </section>

        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">7. Limitation of Liability</h2>
          <p>ZGNAL.AI shall not be liable for any indirect, incidental, or consequential damages arising from use of the Service.</p>
        </section>

        <section>
          <h2 className="text-sm font-mono font-bold text-white mb-3">8. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of the Service constitutes acceptance of updated terms.</p>
        </section>
      </div>
    </div>
  );
}
