import {
  FileText,
  Search,
  Wand2,
  Brain,
  Layers3,
  FileCode,
  Cpu,
} from "lucide-react";

/* Landing-page content data — real engine outputs only. Every image in
   /public/showcase was generated by the pipeline from real research. */

export const SHOWCASE = [
  {
    id: "stablecoin",
    image: "/showcase/stablecoin-brief.png",
    title: "Global Stablecoin Market",
    field: "Digital Finance",
    layout: "Dashboard",
    style: "Executive Institutional",
    aspect: "16:9",
    desc: "Institutional brief mapping $232B market cap, transaction flows, regulatory landscape, and wallet adoption metrics.",
  },
  {
    id: "louvre",
    image: "/showcase/louvre-abu-dhabi-aerial.png",
    title: "Louvre Abu Dhabi Decoded",
    field: "Architecture",
    layout: "Structural Breakdown",
    style: "Aerial Explainer",
    aspect: "16:9",
    desc: "Drone-view isometric cutaway revealing the dome engineering, water channels, and gallery cluster of the $654M Saadiyat Island museum.",
  },
  {
    id: "ai-healthcare",
    image: "/showcase/ai-healthcare-dashboard.png",
    title: "AI in Healthcare 2025",
    field: "Healthcare Intelligence",
    layout: "Dashboard",
    style: "Executive Institutional",
    aspect: "16:9",
    desc: "Multi-panel KPI dashboard tracking drug discovery timelines, diagnostic accuracy, and clinical outcomes across six healthcare sectors.",
  },
  {
    id: "crispr",
    image: "/showcase/crispr-schematic.png",
    title: "CRISPR-Cas9 Gene Editing",
    field: "Molecular Biology",
    layout: "Linear Progression",
    style: "Technical Schematic",
    aspect: "16:9",
    desc: "Blueprint-style schematic showing the five-step molecular process from guide RNA design through DNA repair with success rate data.",
  },
  {
    id: "falcon9",
    image: "/showcase/falcon9-deconstruct.png",
    title: "Falcon 9, Deconstructed",
    field: "Aerospace",
    layout: "Exploded View",
    style: "Deconstruct",
    aspect: "16:9",
    desc: "NYT-style structural breakdown of the reusable launch vehicle — stages, engines, and landing hardware with numbered callouts.",
  },
  {
    id: "ai-market",
    image: "/showcase/ai-market-analysis.png",
    title: "AI Market Analysis 2025",
    field: "Strategy",
    layout: "Dashboard",
    style: "Market Analysis",
    aspect: "16:9",
    desc: "Competitive landscape matrix with $1.8T projected market size, growth drivers, regional leadership, and enterprise adoption curves.",
  },
  {
    id: "transformation",
    image: "/showcase/transformation-roadmap.png",
    title: "Digital Transformation Roadmap",
    field: "Enterprise Strategy",
    layout: "Phased Roadmap",
    style: "Strategy Framework",
    aspect: "16:9",
    desc: "Consulting-grade phased roadmap with milestone markers, workstream lanes, and KPI callouts for a Fortune 500 transformation.",
  },
  {
    id: "ai-dashboard",
    image: "/showcase/ai-market-dashboard.png",
    title: "AI Industry Dashboard",
    field: "Intelligence",
    layout: "Dashboard",
    style: "Executive Institutional",
    aspect: "16:9",
    desc: "Three-trend executive dashboard covering agents vs. chatbots, multimodal dominance, and open-source impact with strategic implications.",
  },
  {
    id: "uae-space",
    image: "/showcase/uae-space-roadmap.png",
    title: "UAE Space Program",
    field: "Space Policy",
    layout: "Timeline",
    style: "Strategy Framework",
    aspect: "16:9",
    desc: "National program timeline from first satellite through Mars mission with budget, agency, and milestone annotations.",
  },
  {
    id: "neural",
    image: "/showcase/neural-networks-schematic.png",
    title: "Neural Network Architecture",
    field: "AI / ML",
    layout: "Hub & Spoke",
    style: "Technical Schematic",
    aspect: "16:9",
    desc: "Four-stage backpropagation walkthrough: forward pass, loss calculation, gradient flow, and weight updates with accuracy timeline.",
  },
];

export const STYLES_SHOWCASE = [
  {
    style: "Executive Institutional",
    technique: "Bento Grid",
    desc: "McKinsey-grade multi-panel dashboard. Data-dense KPI grids with corporate color coding and chart-heavy compositions built for boardrooms.",
    image: "/showcase/style-executive.png",
    accent: "#D4A84B",
  },
  {
    style: "Deconstruct",
    technique: "Exploded View",
    desc: "NYT-style structural breakdown with callout lines, numbered annotations, and isometric dissection.",
    image: "/showcase/style-deconstruct.png",
    accent: "#C04B3C",
  },
  {
    style: "Aerial Explainer",
    technique: "Isometric Cutaway",
    desc: "Drone-perspective architectural rendering with numbered callouts and cross-section views.",
    image: "/showcase/style-aerial.png",
    accent: "#5B8DEF",
  },
  {
    style: "Technical Schematic",
    technique: "Blueprint Process",
    desc: "Engineering-blueprint aesthetic with precise linework, grid backgrounds, and step-by-step process flows.",
    image: "/showcase/style-schematic.png",
    accent: "#8BC34A",
  },
  {
    style: "Craft Handmade",
    technique: "Artisan Roadmap",
    desc: "Warm, illustrated aesthetic with hand-drawn textures, watercolor elements, and winding narrative paths.",
    image: "/showcase/style-craft.png",
    accent: "#A78BFA",
  },
  {
    style: "Strategy Framework",
    technique: "Consulting Canvas",
    desc: "Structured enterprise frameworks with phased roadmaps, milestone markers, and metric callouts.",
    image: "/showcase/style-strategy.png",
    accent: "#E8C96A",
  },
];

export const PIPELINE = [
  {
    num: "01",
    agent: "Sentinel",
    name: "Extract",
    desc: "Parse any format — text, URL, PDF, audio",
    detail:
      "Intelligent content parser handles articles, research papers, raw data, URLs, and file uploads. Strips formatting noise while preserving semantic structure.",
    icon: FileText,
  },
  {
    num: "02",
    agent: "Oracle",
    name: "Research",
    desc: "AI finds real references & verifies facts",
    detail:
      "Routes content to 22 trusted sources — Wikipedia, BBC, WHO, Nature, and more. Every visual claim is verified. Reference images are sourced automatically.",
    highlight: true,
    icon: Search,
  },
  {
    num: "03",
    agent: "Scribe",
    name: "Simplify",
    desc: "Rewrite at 8th-grade reading level",
    detail:
      "NLP rewriting engine distills complex jargon into clear, scannable language. Flesch-Kincaid optimized for maximum comprehension in visual format.",
    icon: Wand2,
  },
  {
    num: "04",
    agent: "Strategist",
    name: "Analyze",
    desc: "Select optimal layout and style combination",
    detail:
      "Content classifier maps topic, density, and hierarchy to the best layout × style pairing from 400+ combinations. Or override with your own selection.",
    icon: Brain,
  },
  {
    num: "05",
    agent: "Architect",
    name: "Structure",
    desc: "Organize content into visual hierarchy",
    detail:
      "Builds the information architecture — decides section order, data visualization types, callout placement, and visual flow based on content type.",
    icon: Layers3,
  },
  {
    num: "06",
    agent: "Forge",
    name: "Prompt",
    desc: "Assemble multimodal generation prompt",
    detail:
      "Constructs a precise Gemini 3 Pro prompt combining text, reference images, style tokens, layout grids, and typography rules into a single payload.",
    icon: FileCode,
  },
  {
    num: "07",
    agent: "Renderer",
    name: "Generate",
    desc: "Render with Gemini 3 Pro + reference images",
    detail:
      "Final render pass generates a high-resolution infographic in ~60 seconds. Output at print resolution (2K+) with consulting-grade visual quality.",
    icon: Cpu,
  },
];

/* Hero specimens — the three lightest real outputs, used output-first above the fold */
export const HERO_SPECIMENS = [
  {
    id: "stablecoin",
    image: "/showcase/stablecoin-brief.png",
    title: "Stablecoin Market Brief",
    style: "Executive Institutional",
    prompt: "a 60-word prompt on stablecoin adoption",
  },
  {
    id: "louvre",
    image: "/showcase/louvre-abu-dhabi-aerial.png",
    title: "Louvre Abu Dhabi Decoded",
    style: "Aerial Explainer",
    prompt: "one Wikipedia URL",
  },
  {
    id: "crispr",
    image: "/showcase/crispr-schematic.png",
    title: "CRISPR-Cas9 Explained",
    style: "Technical Schematic",
    prompt: "a pasted journal abstract",
  },
];
