"use client";

import Image from "next/image";
import { CheckCircle2 } from "lucide-react";
import { SHOWCASE, STYLES_SHOWCASE } from "./landing-content";
import { ScrollReveal } from "./scroll-reveal-v2";

/* Curated, consistently-cropped gallery of REAL engine outputs.
   Replaces the random-width marquee: uniform 16:9 tiles, two featured
   pieces at double size, provenance on every tile. The honesty claim
   ("real research, real data") is promoted to the section's subheading. */
export function OutputGallery() {
  const featured = SHOWCASE.slice(0, 2);
  const grid = SHOWCASE.slice(2);

  return (
    <section id="gallery" className="py-20 sm:py-28 bg-(--z-light)">
      <div className="mx-auto max-w-7xl px-6">
        {/* Header */}
        <div className="mb-12 sm:mb-16 max-w-3xl">
          <ScrollReveal>
            <p className="label-mono text-(--z-gold) mb-4">
              Gallery — real outputs
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <h2 className="text-4xl sm:text-6xl lg:text-7xl font-mono font-medium heading-editorial text-(--z-light-text) mb-5">
              Real research.
              <br />
              <span className="text-(--z-light-muted)">
                Real data. Not mockups.
              </span>
            </h2>
          </ScrollReveal>
          <ScrollReveal delay={0.2}>
            <p className="text-sm text-(--z-light-muted) max-w-lg leading-relaxed">
              Every visual on this page was generated by the engine — researched
              across 22 trusted sources, fact-checked, and rendered at print
              resolution. Nothing here is a design mockup.
            </p>
          </ScrollReveal>
        </div>

        {/* Featured row — two large pieces */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 mb-5">
          {featured.map((item, i) => (
            <ScrollReveal key={item.id} delay={i * 0.08}>
              <figure className="group relative overflow-hidden bg-white terminal-shadow-light">
                <div className="relative aspect-video overflow-hidden">
                  <Image
                    src={item.image}
                    alt={`AI-generated infographic: ${item.title} — ${item.style}`}
                    fill
                    className="object-cover transition-transform duration-700 ease-out group-hover:scale-[1.03]"
                    sizes="(max-width: 1024px) 100vw, 50vw"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  <figcaption className="absolute inset-x-0 bottom-0 p-5 translate-y-2 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-500">
                    <p className="text-sm font-mono font-bold text-white">
                      {item.title}
                    </p>
                    <p className="text-[10px] font-mono uppercase tracking-[0.15em] text-white/60 mt-1">
                      {item.field} · {item.layout} · {item.style}
                    </p>
                  </figcaption>
                </div>
              </figure>
            </ScrollReveal>
          ))}
        </div>

        {/* Grid — uniform 16:9 tiles */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-5">
          {grid.map((item, i) => (
            <ScrollReveal key={item.id} delay={0.05 + (i % 4) * 0.06}>
              <figure className="group relative overflow-hidden bg-white terminal-shadow-light">
                <div className="relative aspect-video overflow-hidden">
                  <Image
                    src={item.image}
                    alt={`AI-generated infographic: ${item.title} — ${item.style}`}
                    fill
                    className="object-cover transition-transform duration-700 ease-out group-hover:scale-[1.04]"
                    sizes="(max-width: 1024px) 50vw, 25vw"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-400" />
                  <figcaption className="absolute inset-x-0 bottom-0 p-3 translate-y-2 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-400">
                    <p className="text-[11px] font-mono font-bold text-white leading-tight">
                      {item.title}
                    </p>
                    <p className="text-[8px] font-mono uppercase tracking-[0.15em] text-white/60 mt-0.5">
                      {item.style}
                    </p>
                  </figcaption>
                </div>
              </figure>
            </ScrollReveal>
          ))}
        </div>

        {/* Provenance line */}
        <ScrollReveal delay={0.15}>
          <p className="flex items-center gap-2 mt-8 text-[11px] font-mono text-(--z-light-muted)">
            <CheckCircle2 className="h-3.5 w-3.5 text-(--z-gold)" />
            Every output ships with a provenance certificate — sources, dates,
            and the exact research trail.
          </p>
        </ScrollReveal>
      </div>

      {/* ── Styles band (#examples) — images ARE the cards ── */}
      <div id="examples" className="mt-20 sm:mt-28">
        <div className="mx-auto max-w-7xl px-6 mb-8">
          <ScrollReveal>
            <p className="label-mono text-(--z-gold) mb-3">Art & Technique</p>
            <h3 className="text-2xl sm:text-4xl font-mono font-medium heading-editorial text-(--z-light-text) max-w-2xl">
              Six visual languages, one engine.
            </h3>
          </ScrollReveal>
        </div>
        {/* Full-bleed horizontal strip, snap-scrolled — captions live ON the image */}
        <div
          tabIndex={0}
          role="region"
          aria-label="Style examples"
          className="overflow-x-auto z-scroll-x scroll-snap-x focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-(--z-gold)"
        >
          <div className="flex gap-4 px-6 pb-4 w-max">
            {STYLES_SHOWCASE.map((item) => (
              <figure
                key={item.style}
                className="relative shrink-0 w-[300px] sm:w-[420px] aspect-[4/3] overflow-hidden group"
              >
                <Image
                  src={item.image}
                  alt={`${item.style} style example — ${item.technique}`}
                  fill
                  loading="lazy"
                  className="object-cover transition-transform duration-700 group-hover:scale-[1.03]"
                  sizes="420px"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
                <figcaption className="absolute inset-x-0 bottom-0 p-4">
                  <span
                    className="inline-block text-[8px] font-mono uppercase tracking-[0.2em] px-2 py-0.5 border mb-2"
                    style={{
                      color: item.accent,
                      borderColor: `${item.accent}55`,
                      backgroundColor: "rgba(0,0,0,0.35)",
                    }}
                  >
                    {item.technique}
                  </span>
                  <p className="text-sm font-mono font-bold text-white">
                    {item.style}
                  </p>
                  <p className="text-[10px] text-white/65 leading-snug mt-1 max-w-[36ch]">
                    {item.desc}
                  </p>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
